[package]
name = "day_2017_14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day_2017_10 = { path = "../day_10" }

[lib]
path = "src/main.rs"
